### ISSUE TITLE
fix sidebar links

### ISSUE THREAD

**Issue by jberkus** [projectatomic/docs.projectatomic.io#6]
Per: https://github.com/projectatomic/atomic-site/issues/301

The sidebar links on the left in the template use the base URL, which means they don't actually work.  Those need an absolute path back to www.projectatomic.io.

@aweiteka , @tigert

**Comment by aweiteka** [comment]
Fixed in https://github.com/openshift/openshift-docs/pull/1883

**Comment by aweiteka** [comment]
https://github.com/openshift/openshift-docs/pull/1883 merged. @jberkus please close.
